### ISSUE TITLE
Compress failed: String index out of range v1.5.1

### ISSUE THREAD

**Issue by shreeshkatyayan** [davidB/yuicompressor-maven-plugin#90]
I am using yuicompressor version 1.5.1.

Following is the pom.xml configuration for the plugin

```
<plugin>
	<groupId>net.alchim31.maven</groupId>
	<artifactId>yuicompressor-maven-plugin</artifactId>
	<version>1.5.1</version>	
	<executions>
		<execution>
			<id>compress</id>
			<phase>package</phase>
			<goals>
				<goal>compress</goal>
			</goals>
		</execution>
	</executions>
	<configuration>
		<nosuffix>true</nosuffix>
		<linebreakpos>-1</linebreakpos>
		<aggregations>
			<aggregation>
				<removeIncluded>true</removeIncluded>
				<insertNewLine>true</insertNewLine>
				<output>${project.build.directory}/${project.build.finalName}/static/js/jquery/jquery.all.min.js</output>
				<includes>
					<include>jquery-1.6.2.min.js</include>
				</includes>
			</aggregation>
		</aggregations>
		<excludes>
			<exclude>**/*.min.js</exclude>
			<exclude>**/push-crew/*.js</exclude>
		</excludes>
	</configuration>
</plugin>
```
I am getting the following error on tracing (-X) on my build process. I tried removing a couple of CSS files which are in the aggregations, but no help. The build process was working fine up until now.

Is this a problem with the plugin? what can be the possible solution? I can't use any other plugin as those are not in our repository. Please help me understand what is wrong here -

```
[ERROR] Failed to execute goal net.alchim31.maven:yuicompressor-maven-plugin:1.5.1:compress (compress) on project LybrateWeb: Execution compress of goal net.alchim31.maven:yuicompressor-maven-plugin:1.5.1:compress failed: String index out of range: 39325 -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal net.alchim31.maven:yuicompressor-maven-plugin:1.5.1:compress (compress) on project LybrateWeb: Execution compress of goal net.alchim31.maven:yuicompressor-maven-plugin:1.5.1:compress failed: String index out of range: 39325
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:225)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution compress of goal net.alchim31.maven:yuicompressor-maven-plugin:1.5.1:compress failed: String index out of range: 39325
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:110)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	... 19 more
```

Thanks in advance

**Comment by lish1986** [comment]
Hi.
I have met the similar problem , have you fixed it already？ If so ,please help me . We can discuss about this together. Thanks
